# Generated by Django 4.2.26 on 2026-07-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0099_issueannotationsnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueannotationsnapshot",
            name="trigger",
            field=models.CharField(choices=[("before", "before")], max_length=16),
        ),
    ]
